### PR TITLE
Getting things ready for #primetime - Documentation Bulk Fixes 1

### PR DESCRIPTION
**Pull request by deavmi**
Made with :heart: and no merge conflicts.

### CODE REVIEW

**Comment by deavmi** [comment]
BTW, I have an install script for Trisquel users that I can add to the building.md file.

**Comment by majestrate** [comment]
i'd like to have proper debian packaging if possible

**Comment by deavmi** [comment]
Okay. Nevermind the script I have decided not to do it anyway.

**Comment by deavmi** [comment]
Done with the docs for now. Take a look at feeds.md and see if anything can be made easier as well as finishing srnd.ini because it really need definitions added for the meaning of each variable in the config file.

**Comment by majestrate** [comment]
can you add .trash to .gitignore and remove the doc/.trash/* files?

**Comment by deavmi** [comment]
Sure

On 05 June 2016 1:54:17 PM SAST, Jeff <notifications@github.com> wrote:
>can you add .trash to .gitignore and remove the doc/.trash/* files?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/majestrate/nntpchan/pull/95#issuecomment-223809013

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deavmi** [comment]
Added .gitignore.

**Comment by majestrate** [comment]
neat

**Comment by deavmi** [comment]
Yep.

**Comment by deavmi** [comment]
Thanks man.

**Pull request merged**
