### PR TITLE
Complete thunderbird-newsreader-configuration.md

### PR DESCRIPTION
**Pull request by nilesr**

### CODE REVIEW

**Comment by majestrate** [comment]
can we bundle the images referenced?

**Comment by nilesr** [comment]
Not 100% sure how to do that. I'll google it and bundle them later today

**Comment by majestrate** [comment]
you can include the files in the `doc` directory with your pull request

**Comment by majestrate** [comment]
i.e. https://github.com/majestrate/nntpchan/blob/3983506fe3018023959fe9c4a80b6252c9c6b73e/doc/moderation.md

**Comment by nilesr** [comment]
Should be bundled now

**Pull request merged**
