### PR TITLE
fix prefixing for overview template

### PR DESCRIPTION
**Pull request by ZiRo-**
This should make i2p.rocks work like it's supposed to.

### CODE REVIEW

**Comment by majestrate** [comment]
it actually doesn't :/

**Comment by majestrate** [comment]
what happens is that it tries to use the post model's unexported field so it panics

**Comment by ZiRo-** [comment]
Well, are you testing with the master branch or the refactor branch?
Because it works when I tried it with master.

**Comment by ZiRo-** [comment]
But it SHOULD work like this, shouldn't it?

**Comment by majestrate** [comment]
perhaps for the ukko page change the prefix parameter passed in to site_prefix

**Pull request merged**
