### PR TITLE
h

### PR DESCRIPTION
**Pull request by deavmi**

### CODE REVIEW

**Comment by majestrate** [comment]
not sure if the redis info is correct or not

**Comment by ZiRo-** [comment]
That's the default redis port. It's filled in by the installer.

**Comment by ZiRo-** [comment]
But regarding the password,
I think it should be
```
echo "requirepass  [password]" >> /path/to/your/redis.conf

**Comment by deavmi** [comment]
Oh yes, sorry `requirepass` i forgot that

**Comment by deavmi** [comment]
and the appending op `>>`

**Comment by deavmi** [comment]
Fixed the Redis password adding code.

**Comment by deavmi** [comment]
Just updated the `cli.md` file.

**Comment by majestrate** [comment]
looks good

**Comment by deavmi** [comment]
Thanks man.

**Pull request merged**
