### PR TITLE
d

### PR DESCRIPTION
**Pull request by deavmi**

### CODE REVIEW

**Comment by deavmi** [comment]
Umh. Close this probably. Mistake.

**Comment by deavmi** [comment]
Not done just yet.

**Comment by deavmi** [comment]
You can probably merge this one.

**Comment by deavmi** [comment]
If there is any problem with merging I can fix them soon.

**Comment by majestrate** [comment]
there's still some merge conflicts

**Comment by deavmi** [comment]
Mmmm. What is not merging?

**Comment by deavmi** [comment]
Of I see.

**Comment by deavmi** [comment]
Made a new pull request that sorts out the newsreader file.

**Comment by deavmi** [comment]
Keep this open so I can check if all is transferred to the new PRs I have made (which you can merge now),

**Comment by deavmi** [comment]
Never mind.I think all is done.

**Pull request closed without merging**
